# Stage 1
FROM node:16 as build-stage

WORKDIR /ui
COPY package.json .
RUN npm install
COPY . .

RUN npm run build

# Stage 2
FROM nginx

COPY --from=build-stage /ui/build /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf
EXPOSE 80

CMD nginx -g 'daemon off;'